### PR TITLE
Fix DPP bug

### PR DESCRIPTION
**Pull request by magnified103**

### CODE REVIEW

**Comment by feherneoh** [comment]
Let me just ask one simple thing? What is the point in making the code larger and slower for every device, when what you are trying to "fix" is not something that should be fixed by software, and the code you are modifying is something that will be dropped in the near future?

Oh, and please list me the cases that this change fixes, because the only such case I know about is RM-998 being identified as RM-914, and that could be fixed in like 4 lines.

**Comment by magnified103** [comment]
First, @sjrmac said to me that this bug happened on lumia 525 and 720. Second, i am a very stupid coder. Third, this won't make the device slower since the rom only check it on installing.

**Comment by feherneoh** [comment]
This code runs on every boot, not only when installing the ROM, and as a library used by init, it stays in RAM until you shut the device down

**Comment by magnified103** [comment]
Oh

**Comment by magnified103** [comment]
If my codes are too long or stupid or something like that, you can stop my pull request now and fix it yourself XD

**Comment by feherneoh** [comment]
I'll fix the 525 one when I have time, 720 MUST BE fixed on-device, as this bug breaks WDRT detection too

**Pull request closed without merging**
